apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-clusterip
  labels:
    {{- include "hello-kubernetes.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "hello-kubernetes.selectorLabels" . | nindent 4 }}
